[package]
name = "serial"
version = "0.1.0"
edition = "2024"

[dependencies]
serialport = "4.3.0"
regex = "1"
once_cell = "1"
chrono = "0.4"
parking_lot = "0.12.4"
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
